// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index(page templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"nl\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=3.0\"><meta name=\"csrf\" content=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(GetCSRF(ctx))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ports/templates/index.templ`, Line: 9, Col: 43}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><title>Berekeningen Aquila A210</title><script src=\"js/htmx.min.js\"></script><script src=\"js/flatpickr.js\"></script><script src=\"js/download.js\"></script><link rel=\"icon\" href=\"data:image/svg+xml,&lt;svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22&gt;&lt;text y=%221em%22 font-size=%2280%22&gt;🛫&lt;/text&gt;&lt;/svg&gt;\"><link rel=\"stylesheet\" href=\"css/material-icons.css\"><link rel=\"stylesheet\" href=\"css/flatpickr.min.css\"><link href=\"css/style.min.css\" rel=\"stylesheet\"></head><body class=\"bg-white\"><header class=\"bg-indigo-600 text-white fixed w-full top-0 z-50\"><div class=\"max-w-7xl mx-auto px-2\"><div class=\"flex justify-between h-16\"><div class=\"flex\"><div class=\"ml-2 flex items-center\"><span hx-trigger=\"click\" hx-get=\"/\" hx-target=\"#content-container\" hx-swap=\"outerHTML\" class=\"cursor-pointer text-lg font-semibold uppercase\">&#128747; Berekeningen</span></div></div><div class=\"flex items-center\"><a target=\"_blank\" href=\"https://www.pay.nl/doneren/SL-8940-9333/0Lc03af/?amount_min=100&amp;amount=500\" class=\"flex items-center bg-indigo-500 text-white font-semibold py-2 px-4 rounded-sm hover:bg-indigo-400 transition duration-300 ease-in-out no-print\"><span class=\"material-icons mr-2\">favorite</span>Doneer</a></div></div></div></header><main class=\"max-w-7xl mx-auto mt-16 p-4 pb-20\"><div class=\"flex flex-col lg:items-stretch w-full\" id=\"#main\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = page.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></main><footer class=\"fixed bottom-0 left-0 w-full text-center py-2 bg-gray-100 text-gray-600 text-sm\"><a href=\"https://github.com/michaelvlaar/ppl-calculations\" target=\"_blank\" class=\"hover:text-gray-800 inline-flex items-center space-x-2\"><img alt=\"github\" src=\"images/github-mark.svg\" width=\"15px\" height=\"15px\"> <span>michaelvlaar/ppl-calculations (")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(GetVersion(ctx))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ports/templates/index.templ`, Line: 51, Col: 59}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, ")</span></a><div class=\"mt-1\">&copy; 2024 Michael Vlaar</div></footer><script src=\"js/csrf.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
