// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type StepperStep int

const (
	StepperStepWeight StepperStep = iota
	StepperStepFuel
	StepperStepCalculations
	StepperStepExport
)

func Stepper(step StepperStep) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"stepper\" class=\"flex w-full mb-4\"><div class=\"flex w-full\"><ul class=\"w-full relative flex flex-row\"><li class=\"flex items-center gap-x-2 shrink basis-0 flex-1 group\"><div class=\"min-h-7 inline-flex justify-center items-center text-xs align-middle\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		switch step {
		case StepperStepWeight:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<span class=\"bg-indigo-600 flex justify-center items-center shrink-0 border border-gray-400 font-medium text-gray-800 rounded-full text-white\"><span class=\"material-icons text-white p-2\">create</span></span> <span class=\"ml-2 ms-2 hidden sm:block text-sm font-medium text-gray-800\">Invoeren</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		default:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<form class=\"flex w-full\" hx-get=\"/load\" hx-target=\"#content-container\" hx-swap=\"outerHTML scroll:top\"><input type=\"hidden\" name=\"submit\" value=\"weight\"> <button id=\"stepper-back-weight\" type=\"submit\" class=\"cursor-pointer bg-indigo-600 flex justify-center items-center shrink-0 border border-gray-400 font-medium text-gray-800 rounded-full text-white\"><span class=\"material-icons text-white p-2\">create</span></button> <button type=\"submit\" class=\"cursor-pointer ml-2 ms-2 hidden sm:block text-sm font-medium text-gray-800\">Invoeren</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><div class=\"mr-2 w-full h-px flex-1 bg-gray-400 group-last:hidden\"></div></li><li class=\"flex items-center gap-x-2 shrink basis-0 flex-1 group\"><div class=\"min-w-7 min-h-7 inline-flex justify-center items-center text-xs align-middle\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		switch step {
		case StepperStepWeight:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<span class=\"flex justify-center items-center shrink-0 border border-gray-400 font-medium text-gray-800 rounded-full\"><span class=\"material-icons p-2\">local_gas_station</span></span> <span class=\"ml-2 ms-2 hidden sm:block text-sm font-medium text-gray-800\">Brandstof</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case StepperStepFuel:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<span class=\"bg-indigo-600 flex justify-center items-center shrink-0 border border-gray-400 font-medium text-gray-800 rounded-full\"><span class=\"text-white material-icons p-2\">local_gas_station</span></span> <span class=\"ml-2 ms-2 hidden sm:block text-sm font-medium text-gray-800\">Brandstof</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		default:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<form class=\"flex w-full\" hx-get=\"/fuel\" hx-target=\"#content-container\" hx-swap=\"outerHTML scroll:top\"><input type=\"hidden\" name=\"submit\" value=\"fuel\"> <button type=\"submit\" id=\"stepper-back-fuel\" class=\"cursor-pointer bg-indigo-600 flex justify-center items-center shrink-0 border border-gray-400 font-medium text-gray-800 rounded-full\"><span class=\"material-icons text-white p-2\">local_gas_station</span></button> <button type=\"submit\" class=\"cursor-pointer ml-2 ms-2 hidden sm:block text-sm font-medium text-gray-800\">Brandstof</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div><div class=\"mr-2 w-full h-px flex-1 bg-gray-400 group-last:hidden\"></div></li><li class=\"flex items-center gap-x-2 shrink basis-0 flex-1 group\"><div class=\"min-w-7 min-h-7 inline-flex justify-center items-center text-xs align-middle\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		switch step {
		case StepperStepWeight:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<span class=\"flex justify-center items-center shrink-0 border border-gray-400 font-medium text-gray-800 rounded-full\"><span class=\"material-icons p-2\">bar_chart</span></span> <span class=\"ml-2 ms-2 hidden sm:block text-sm font-medium text-gray-800\">Berekeningen</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case StepperStepFuel:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<span class=\"flex justify-center items-center shrink-0 border border-gray-400 font-medium text-gray-800 rounded-full\"><span class=\"material-icons p-2\">bar_chart</span></span> <span class=\"ml-2 ms-2 hidden sm:block text-sm font-medium text-gray-800\">Berekeningen</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case StepperStepCalculations:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<span class=\"bg-indigo-600 flex justify-center items-center shrink-0 border border-gray-400 font-medium text-gray-800 rounded-full\"><span class=\"text-white material-icons p-2\">bar_chart</span></span> <span class=\"ml-2 ms-2 hidden sm:block text-sm font-medium text-gray-800\">Berekeningen</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case StepperStepExport:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<form class=\"flex w-full\" hx-get=\"/stats\" hx-target=\"#content-container\" hx-swap=\"outerHTML scroll:top\"><input type=\"hidden\" name=\"submit\" value=\"stats\"> <button type=\"submit\" id=\"stepper-back-stats\" class=\"cursor-pointer bg-indigo-600 flex justify-center items-center shrink-0 border border-gray-400 font-medium text-gray-800 rounded-full\"><span class=\"material-icons text-white p-2\">bar_chart</span></button> <button type=\"submit\" class=\"cursor-pointer ml-2 ms-2 hidden sm:block text-sm font-medium text-gray-800\">Berekeningen</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div><div class=\"mr-2 w-full h-px flex-1 bg-gray-400 group-last:hidden dark:bg-neutral-700\"></div></li><li class=\"flex items-center shrink basis-0 group\"><div class=\"min-w-7 min-h-7 inline-flex justify-center items-center text-xs align-middle\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		switch step {
		case StepperStepExport:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<span class=\"bg-indigo-600 flex justify-center items-center shrink-0 border border-gray-400 font-medium text-gray-800 rounded-full\"><span class=\"material-icons p-2 text-white\">save_alt</span></span> <span class=\"ml-2 ms-2 hidden sm:block text-sm font-medium text-gray-800\">Opslaan</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		default:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<span class=\"flex justify-center items-center shrink-0 border border-gray-400 font-medium text-gray-800 rounded-full\"><span class=\"material-icons p-2\">save_alt</span></span> <span class=\"ml-2 ms-2 hidden sm:block text-sm font-medium text-gray-800\">Opslaan</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</div></li></ul></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
