// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "ppl-calculations/ports/templates/models"

func WeightAndBalanceWindOption(weight models.WindOption) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"mb-4\" id=\"wind-option\"><label for=\"wind\" class=\"uppercase block text-gray-700 font-bold mb-2\">Wind (kts)</label><div class=\"flex\"><input type=\"number\" id=\"wind\" min=\"0\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if equalsPointer(weight.WindDirection, "tailwind") {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " max=\"10\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " max=\"20\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " placeholder=\"Wind (kts)\" id=\"wind\" name=\"wind\" required")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if weight.Wind != nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, " value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(*weight.Wind)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `ports/templates/weight-and-balance.templ`, Line: 23, Col: 25}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, " class=\"shadow-sm mr-2 appearance-none border rounded-sm w-full py-2 px-3 text-gray-700 leading-tight focus:outline-hidden focus:shadow-outline\"> <select aria-label=\"Windrichting\" id=\"wind-direction\" hx-get=\"/wind-option\" hx-trigger=\"change\" hx-target=\"#wind-option\" hx-include=\"[name=&#39;wind&#39;],[name=&#39;wind_direction&#39;]\" name=\"wind_direction\" required class=\"custom-select shadow-sm appearance-none border rounded-sm w-full py-2 px-3 text-gray-700 leading-tight focus:outline-hidden focus:shadow-outline cursor-pointer\"><option value=\"headwind\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !equalsPointer(weight.WindDirection, "tailwind") {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, ">Tegenwind</option> <option value=\"tailwind\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if equalsPointer(weight.WindDirection, "tailwind") {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, ">Rugwind</option></select></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func WeightAndBalanceForm(weight models.Weight) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<div class=\"w-full flex flex-col\" id=\"content-container\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Stepper(StepperStepWeight).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<form class=\"w-full mb-2 flex flex-col\" id=\"main-form\" hx-post=\"/load\" hx-target=\"#content-container\" hx-swap=\"outerHTML show:top\"><div class=\"flex flex-col sm:flex-row\"><div class=\"w-full flex flex-col sm:mr-2\"><div class=\"mb-4\"><label for=\"callsign\" class=\"uppercase block text-gray-700 font-bold mb-2\">Vliegtuig</label> <select id=\"callsign\" name=\"callsign\" class=\"custom-select shadow-sm appearance-none border rounded-sm w-full py-2 px-3 text-gray-700 leading-tight focus:outline-hidden focus:shadow-outline cursor-pointer\" required><option value=\"PHDHA\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if equalsPointer(weight.CallSign, "PHDHA") {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, ">PHDHA</option> <option value=\"PHDHB\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if equalsPointer(weight.CallSign, "PHDHB") {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, ">PHDHB</option></select></div><div class=\"flex w-full\"><div class=\"mb-4 w-1/2 mr-1\"><label for=\"piloot-gewicht\" class=\"uppercase block text-gray-700 font-bold mb-2\">Piloot (kg)</label> <input type=\"number\" placeholder=\"Gewicht piloot in kg\" min=\"0\" id=\"piloot-gewicht\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if weight.Pilot != nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, " value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(*weight.Pilot)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `ports/templates/weight-and-balance.templ`, Line: 65, Col: 30}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, " name=\"pilot\" class=\"shadow-sm appearance-none border rounded-sm w-full py-2 px-3 text-gray-700 leading-tight focus:outline-hidden focus:shadow-outline\" required></div><div class=\"mb-4 w-1/2 ml-1\"><label for=\"pilot-seat\" class=\"uppercase block text-gray-700 font-bold mb-2\">Stoel Positie</label> <select id=\"pilot-seat\" name=\"pilot_seat\" class=\"custom-select shadow-sm appearance-none border rounded-sm w-full py-2 px-3 text-gray-700 leading-tight focus:outline-hidden focus:shadow-outline cursor-pointer\" required><option value=\"b\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if equalsPointer(weight.PilotSeat, "b") {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, ">Achter</option> <option value=\"m\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if equalsPointer(weight.PilotSeat, "m") {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, ">Midden</option> <option value=\"f\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if equalsPointer(weight.PilotSeat, "f") {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, ">Voor</option></select></div></div><div class=\"w-full flex\"><div class=\"mb-4 w-1/2 mr-1\"><label for=\"passagier-gewicht\" class=\"uppercase block text-gray-700 font-bold mb-2\">Passagier (kg)</label> <input type=\"number\" min=\"0\" placeholder=\"Gewicht passagier in kg\" id=\"passagier-gewicht\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if weight.Passenger != nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, " value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(*weight.Passenger)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `ports/templates/weight-and-balance.templ`, Line: 98, Col: 34}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, " name=\"passenger\" class=\"shadow-sm appearance-none border rounded-sm w-full py-2 px-3 text-gray-700 leading-tight focus:outline-hidden focus:shadow-outline\"></div><div class=\"mb-4 w-1/2 ml-1\"><label for=\"passenger-seat\" class=\"uppercase block text-gray-700 font-bold mb-2\">Stoel Positie</label> <select id=\"passenger-seat\" name=\"passenger_seat\" class=\"custom-select shadow-sm appearance-none border rounded-sm w-full py-2 px-3 text-gray-700 leading-tight focus:outline-hidden focus:shadow-outline cursor-pointer\" required><option value=\"b\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if equalsPointer(weight.PassengerSeat, "b") {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, ">Achter</option> <option value=\"m\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if equalsPointer(weight.PassengerSeat, "m") {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, ">Midden</option> <option value=\"f\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if equalsPointer(weight.PassengerSeat, "f") {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, ">Voor</option></select></div></div><div class=\"mb-4\"><label for=\"bagage-gewicht\" class=\"uppercase block text-gray-700 font-bold mb-2\">bagage (kg, max. 40)</label> <input type=\"number\" min=\"0\" max=\"40\" placeholder=\"Gewicht bagage in kg\" id=\"bagage-gewicht\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if weight.Baggage != nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, " value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(*weight.Baggage)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `ports/templates/weight-and-balance.templ`, Line: 133, Col: 31}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 37, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 38, " name=\"baggage\" required class=\"shadow-sm appearance-none border rounded-sm w-full py-2 px-3 text-gray-700 leading-tight focus:outline-hidden focus:shadow-outline\"></div></div><div class=\"w-full flex flex-col sm:ml-2\"><div class=\"mb-4\"><label for=\"oat\" class=\"uppercase block text-gray-700 font-bold mb-2\">Buitentemperatuur (&deg;C)</label> <input type=\"number\" min=\"-30\" max=\"40\" placeholder=\"Buitentemperatuur in °C\" min=\"0\" id=\"oat\" name=\"oat\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if weight.OutsideAirTemperature != nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 39, " value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(*weight.OutsideAirTemperature)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `ports/templates/weight-and-balance.templ`, Line: 156, Col: 45}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 40, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 41, " class=\"shadow-sm appearance-none border rounded-sm w-full py-2 px-3 text-gray-700 leading-tight focus:outline-hidden focus:shadow-outline\" required></div><div class=\"mb-4\"><label for=\"pressure-altitude\" class=\"uppercase block text-gray-700 font-bold mb-2\">Drukhoogte (Voeten)</label> <input type=\"number\" min=\"0\" max=\"8000\" placeholder=\"Drukhoogte in voeten\" id=\"pressure-altitude\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if weight.PressureAltitude != nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 42, " value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(*weight.PressureAltitude)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `ports/templates/weight-and-balance.templ`, Line: 174, Col: 40}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 43, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 44, " name=\"pressure_altitude\" required class=\"shadow-sm appearance-none border rounded-sm w-full py-2 px-3 text-gray-700 leading-tight focus:outline-hidden focus:shadow-outline\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = WeightAndBalanceWindOption(models.WindOption{
			Wind:          weight.Wind,
			WindDirection: weight.WindDirection,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 45, "</div></div><div class=\"mt-4 flex items-center justify-between\"><div hx-trigger=\"click\" hx-get=\"/\" hx-target=\"#content-container\" hx-swap=\"outerHTML\" class=\"cursor-pointer mr-1 text-center w-full bg-gray-200 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded-sm focus:outline-hidden focus:shadow-outline\">Vorige</div><input name=\"submit\" value=\"Volgende\" type=\"submit\" class=\"cursor-pointer w-full bg-indigo-600 hover:bg-indigo-800 text-white font-bold py-2 px-4 rounded-sm focus:outline-hidden focus:shadow-outline\"></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
